# Site settings
title: Liney
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liney.io" # the base hostname & protocol for your site
twitter_username: lineyjane
github_username:  carolineclark

# Build settings
markdown: kramdown
exclude: [vendor]
